# GitHub Sponsors / Patrocinio

# Si deseas añadir opciones de patrocinio, descomenta y completa las siguientes líneas:

# github: [ergrato-dev]
# patreon: usuario
# ko_fi: usuario
# custom: ['https://www.ejemplo.com/donate']

# Este es un proyecto educativo del SENA
# No se solicita patrocinio financiero
